@extends('layouts.frontend')
@section('title', 'privacy policy')
@section('content')

 
<main id="main">
    <div class="container">
        <br><br><br><br>
        
        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong>Privacy Policy</strong>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>Effective date: 06/10/2023&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>Welcome to <strong>The Cooperatives Trust</strong> (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;). We value your trust and are committed to protecting your privacy. This Privacy Policy outlines how we collect, use, disclose, and safeguard your personal information when you use our website (<strong>www.coopindia.org</strong>) and services. By accessing or using our website, you consent to the practices described in this policy.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong><u>1. Information we collect</u></strong>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>a. Personal Information: We may collect personal information that you provide directly to us when you use our website or services. This information may include, but is not limited to:</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp; &nbsp; - Name, address, date of birth, and contact information.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp; &nbsp; - Social Security Number (SSN) or other government-issued identification numbers.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp; &nbsp; - Financial information, credit history, and credit scores.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp; &nbsp; - Employment details.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp; &nbsp; - Information about your interactions with us, including customer support inquiries.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>b. Cookies and Similar Technologies: When you visit our website, we may use cookies and similar technologies to collect certain information automatically. This information may include your IP address, browser type, device identifiers, browsing history, and website usage patterns.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong><u>2. How we use your information</u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>a. Provide Services: We use your personal information to provide you with our credit reporting services, including credit reports, education, and related products.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>b. Improve Services: We may use your information to enhance and personalize our services, optimize website performance, and develop new features and offerings.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>c. Communication: We may use your contact information to send you important updates, service notifications, promotional offers, and marketing communications that we believe may be of interest to you. You have the option to opt-out of marketing communications.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>d. Legal Obligations: We may use and disclose your information to comply with applicable laws, regulations, legal processes, or government requests.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>e. Security: We use your information to protect our website, systems, and customers from potential security threats and fraud.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong><u>3. Information Sharing and Disclosure</u></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>a. Third-party Service Providers: We may share your personal information with third-party service providers that help us operate our business, provide services on our behalf, and improve our website.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>b. Legal Requirements: We may disclose your information if required by law or in response to a valid legal request, such as a subpoena or court order.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>c. Business Transactions: In the event of a merger, acquisition, or sale of all or a portion of our assets, your information may be transferred to the acquiring entity.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong><u>4. Your Choices</u></strong>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>a. Access and Update Information: You have the right to access and update your personal information. If you believe that any information we have about you is inaccurate, please contact us to correct it.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>b. Opt-out: You can opt-out of receiving marketing communications from us by following the instructions provided in our communications or by contacting us directly.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong><u>5. Security</u></strong>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>We implement reasonable security measures to protect your personal information from unauthorized access, disclosure, alteration, or destruction. However, no method of transmission over the internet or electronic storage is entirely secure, and we cannot guarantee absolute security.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong><u>6. Children&apos;s Privacy</u></strong>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>Our services are not intended for individuals under the age of 18. We do not knowingly collect personal information from children. If you are a parent or guardian and believe that your child has provided us with personal information, please contact us, and we will delete the information from our records.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong><u>7. Changes to this Privacy Policy</u></strong>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>We may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. We will notify you of any material changes through a prominent notice on our website or other appropriate means.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong><u>8. Contact Us</u></strong>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>If you have any questions, concerns, or requests regarding this Privacy Policy or our privacy practices, please contact us at:&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'><strong>thecooperativestrust@gmail.com</strong>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>Thank you for trusting <strong>The Cooperatives Trust</strong>. We are dedicated to safeguarding your personal information and ensuring your privacy is respected.</p>
        
 
    </div>
</main>
 
@endsection