@extends('layouts.frontend')
@section('title', 'Services')
@section('content')

<main id="main">
    <div class="container">
<br><br><br><br>

<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>Refund Policy&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>Effective Date: 06/10/2023&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>Thank you for using the services of <strong>The Cooperatives Trust</strong> (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). We strive to provide you with the best possible experience while using our credit reporting services. This Refund Policy outlines the terms and conditions for obtaining refunds for our products and services. Please read this policy carefully before using our services. By accessing our website or using our services, you agree to adhere to the terms of this Refund Policy.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>1. Refund Eligibility&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>a. Credit Reports and Education: We offer credit reports and education as part of our services. It is essential to understand that the data provided in these reports and education are based on information obtained from various sources, including credit bureaus, societies, cooperatives, financial institutions and other third party agencies. While we make every effort to ensure accuracy, we cannot guarantee the outcome of any credit-related decisions based on the reports or scores.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>b. Refund Criteria: Our services are generally non-refundable due to the nature of the information provided. However, we may consider issuing a refund in the following situations:&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp; &nbsp; - Duplicate Charge: If you believe you were charged twice for the same product or service, please contact our customer support within 3 days of the transaction. We will investigate the matter, and if the duplicate charge is verified, we will issue a refund for the duplicate amount.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp; &nbsp; - Service Unavailability: In the rare event that our services become unavailable due to unforeseen technical issues or other circumstances beyond our control, and you were unable to access the purchased product or service, you may be eligible for a refund. Please contact our customer support within 3 days of the incident to initiate a refund review.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>2. Refund Request Process&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>a. Contact Customer Support: To request a refund, please contact our customer support team via mail (thecooperativestrust@gmail.com). Provide your name, transaction details, and a clear explanation of the reason for the refund request.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>b. Refund Review: Once we receive your refund request, our team will review the information provided and verify whether it meets the eligibility criteria outlined in this policy.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>&nbsp;c. Refund Notification: We will notify you of the decision regarding your refund request within 7 days of receiving your request. If your refund is approved, we will process the refund to the original payment method used for the purchase.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>3. Non-Refundable Circumstances&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>a. Change of Mind: We do not issue refunds for requests made due to a change of mind or if you decide you no longer require our services.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>b. Data Accuracy: While we strive for accuracy and quality in our services, we cannot guarantee the accuracy of the data obtained from third-party sources. Refunds will not be provided based on discrepancies or errors in the data provided.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>c. Third-party Fees: Any third-party fees associated with the purchase, such as credit card processing fees, are non-refundable.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>4. Contact Us&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>If you have any questions, concerns, or requests regarding our Refund Policy, please contact our customer support team via:&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>thecooperativestrust@gmail.com&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>5. Changes to this Refund Policy&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>We may update this Refund Policy periodically to reflect changes in our services or legal requirements. Any modifications to this policy will be effective upon posting on our website.&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;font-family:"Calibri","sans-serif";text-align:justify;'>Thank you for choosing <strong>The Cooperatives Trust</strong> Services. We are committed to providing you with reliable credit reporting services and assisting you with any refund inquiries within the scope of this policy.</p>

    </div>
</main>

@endsection